
###
# @name hello_with_no_auth
# @expect_status 401
GET {{app_url}}/hello

?? status == 401

###
# @name hello_get_with_auth
# @expect_status 200
GET {{app_url}}/hello
Authorization: {{authorization}}

?? status == 200

###
# @name root_with_no_auth
# @expect_status 200
GET {{app_url}}

?? status == 200

###
# @name beowser_with_no_auth
# @expect_status 401
GET {{app_url}}/browser

?? status == 401

###
# @name browser_get_with_auth
# @expect_status 200
GET {{app_url}}/browser
Authorization: {{authorization}}  

?? status == 200

###
# @name CMIS_list_root
# @expect_status 200
GET {{app_url}}/browser/test/root/
Authorization: {{authorization}}

?? status == 200

###
# @name CMIS_create_folder
# @expect_status 201
POST {{app_url}}/browser/test/root
Authorization: {{authorization}}
content-type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="cmisaction"

createfolder
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[0]"

cmis:objectTypeId
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[0]"

cmis:folder
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[1]"

cmis:name
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[1]"

test
--WebKitFormBoundary--

?? status == 201

###
# @name CMIS_list_test
# @expect_status 200
GET {{app_url}}/browser/test/root/test
Authorization: {{authorization}}

?? status == 200

###
# @name CMIS_create_document
# @expect_status 201
POST {{app_url}}/browser/test/root/test
Authorization: {{authorization}}
content-type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="cmisaction"

createdocument
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[0]"

cmis:objectTypeId
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[0]"

cmis:document
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[1]"

cmis:name
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[1]"

hello.txt
--WebKitFormBoundary
Content-Disposition: form-data; name="versioningState"

none
--WebKitFormBoundary
Content-Disposition: form-data; name="content"; filename=myDoc.txt
Content-Type: text/plain
Content-Transfer-Encoding: binary

Hello World!
--WebKitFormBoundary--

?? status == 201

###
# @name CMIS_get_hello.txt
# @expect_status 200
GET {{app_url}}/browser/test/root/test/hello.txt
Authorization: {{authorization}}

?? status == 200

###
# @name CMIS_create_folder_2
# @expect_status 201
POST {{app_url}}/browser/test/root
Authorization: {{authorization}}
content-type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="cmisaction"

createfolder
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[0]"

cmis:objectTypeId
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[0]"

cmis:folder
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[1]"

cmis:name
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[1]"

TestFolder-2656-90
--WebKitFormBoundary--

?? status == 201

###
# @name CMIS_create_document_2
# request from process automation 
# objectId is encoded twice
# @expect_status 201
POST {{app_url}}/browser/test/root?objectId=L1Rlc3RGb2xkZXItMjY1Ni05MA%253d%253d
Authorization: {{authorization}}
content-type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="cmisaction"

createdocument
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[0]"

cmis:objectTypeId
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[0]"

cmis:document
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyId[1]"

cmis:name
--WebKitFormBoundary
Content-Disposition: form-data; name="propertyValue[1]"

hello.txt
--WebKitFormBoundary
Content-Disposition: form-data; name="versioningState"

none
--WebKitFormBoundary
Content-Disposition: form-data; name="content"; filename=myDoc.txt
Content-Type: text/plain
Content-Transfer-Encoding: binary

Hello World!
--WebKitFormBoundary--

?? status == 201